version: 2
jobs:
  build:
    docker:
      - image: node:10
    working_directory: ~/web
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Lint
          command: npm run lint --silent
      - run:
          name: Test
          command: npm test
      - run:
          name: Build website
          command: |
            npm run build
      - store_artifacts:
          path: ~/web/docs
          destination: docs
      - persist_to_workspace:
          root: /home/circleci/web
          paths:
            - docs
  deploy:
    docker:
      - image: node:10
    working_directory: ~/web
    steps:
      - attach_workspace:
          at: /home/circleci/web
      - run:
          name: Install gh-pages
          command: npm install -g --silent gh-pages@2.0.1
      - run:
          name: Configure Git
          command: |
            git config --global user.name "StackStorm Exchange"
            git config --global user.email "info@stackstorm.com"
      - run:
          name: Deploy updated site
          command: gh-pages --message "[skip ci] Website updates" --dist docs
workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master